# Generated by Django 5.2.16 on 2026-07-29 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=180)),
                ('role', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, default='', max_length=180)),
                ('salary_range', models.CharField(blank=True, default='', max_length=120)),
                ('job_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='saved', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=80)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
